// neighborhoodsConfig.js
const neighborhoods = [
    { name: "Alki/Admiral", id: 1.4 },
    { name: "Arbor Heights", id: 1.1 },
    { name: "Ballard", id: 10.4 },
    { name: "Beacon Hill", id: 3.5 },
    { name: "Belltown", id: 13.1 },
    { name: "Broadview/Bitter Lake", id: 9.1 },
    { name: "Capitol Hill", id: 6.2 },
    { name: "Cascade/Eastlake", id: 11.3 },
    { name: "Cedar Park/Meadowbrook", id: 8.3 },
    { name: "Central Area/Squire Park", id: 5.3 },
    { name: "Columbia City", id: 4.2 },
    { name: "Downtown Commercial Core", id: 13.2 },
    { name: "Duwamish/SODO", id: 3.3 },
    { name: "Fauntleroy/Seaview", id: 1.2 },
    { name: "First Hill", id: 6.1 },
    { name: "Fremont", id: 11.1 },
    { name: "Georgetown", id: 3.2 },
    { name: "Green Lake", id: 9.4 },
    { name: "Greenwood/Phinney Ridge", id: 9.3 },
    { name: "Haller Lake", id: 9.5 },
    { name: "High Point", id: 2.2 },
    { name: "Highland Park", id: 2.5 },
    { name: "Interbay", id: 12.2 },
    { name: "Judkins Park", id: 5.2 },
    { name: "Laurelhurst/Sand Point", id: 7.5 },
    { name: "Licton Springs", id: 9.2 },
    { name: "Madison Park", id: 6.5 },
    { name: "Madrona/Leschi", id: 5.1 },
    { name: "Magnolia", id: 12.1 },
    { name: "Miller Park", id: 6.4 },
    { name: "Montlake/Portage Bay", id: 7.1 },
    { name: "Mt. Baker/North Rainier", id: 4.4 },
    { name: "North Beacon Hill/Jefferson Park", id: 3.6 },
    { name: "North Beach/Blue Ridge", id: 10.1 },
    { name: "North Capitol Hill", id: 6.3 },
    { name: "North Delridge", id: 2.1 },
    { name: "Northgate/Maple Leaf", id: 8.1 },
    { name: "Olympic Hills/Victory Heights", id: 8.2 },
    { name: "Pioneer Square/International District", id: 13.3 },
    { name: "Queen Anne", id: 12.3 },
    { name: "Rainier Beach", id: 4.1 },
    { name: "Ravenna/Bryant", id: 7.3 },
    { name: "Riverview", id: 2.3 },
    { name: "Roxhill/Westwood", id: 2.4 },
    { name: "Seward Park", id: 4.3 },
    { name: "South Beacon Hill/NewHolly", id: 3.4 },
    { name: "South Park", id: 3.1 },
    { name: "Sunset Hill/Loyal Heights", id: 10.3 },
    { name: "University District", id: 7.2 },
    { name: "Wallingford", id: 11.2 },
    { name: "Wedgwood/View Ridge", id: 7.4 },
    { name: "West Seattle Junction/Genesee Hill", id: 1.3 },
    { name: "Whittier Heights", id: 10.2 },
];

export default neighborhoods;
